### ISSUE TITLE
シンボル表記で書こう

### ISSUE THREAD

**Issue by norotime** [yagupi/k-board#10]
https://github.com/yagupi/k-board/blob/2b68b07bd1971a43e57d470884124a73c503c690/app/controllers/blogs_controller.rb#L27

```
シンボルを使うメリットは

新しく文字列を生成しない分やや効率がよく、比較も高速。
文字の意味がはっきりするのでコードが読みやすくなる
immutable なので内容を書き換えられる心配がない
```

https://docs.ruby-lang.org/ja/latest/class/Symbol.html

**Comment by yagupi** [comment]
一部シンボル表記も混在していましたが、各Controllerのrenderメソッドはシンボル表記に修正しました。
'new'　→　:new　、　'edit'　→　:edit
