### ISSUE TITLE
danger属性はデフォルトでは使えないはずなので要検討する

### ISSUE THREAD

**Issue by norotime** [yagupi/k-board#13]
https://github.com/yagupi/k-board/blob/master/app/controllers/sessions_controller.rb#L11

https://api.rubyonrails.org/classes/ActionDispatch/Flash.html

**Comment by yagupi** [comment]
[:danger]を[:alert]に修正しました。
ログイン画面へのメッセージ表示が抜けていたので併せて追加しました。
