### ISSUE TITLE
returnはRubyでは明示的に記述しなくても良いことがある

### ISSUE THREAD

**Issue by norotime** [yagupi/k-board#16]
https://github.com/yagupi/k-board/blob/2b68b07bd1971a43e57d470884124a73c503c690/app/controllers/users_controller.rb#L76

https://docs.ruby-lang.org/ja/latest/doc/spec=2fcontrol.html#return

**Comment by yagupi** [comment]
ここでのreturnは、each文でインスタンスを作り続けるのを、エラーレコードがあった時点で中断させるための処理として入れています。
returnを入れないと、エラーレコードを抜いたレコードで中途半端なsaveを避けるためなのですが、他の中断方法が分かりませんでした。
returnが必要な場合には記述するという理解や、別の手段を選ぶべきなどご指摘あればご教示ください。

**Comment by norotime** [comment]
@yagupi わかりました〜。
