### ISSUE TITLE
コミットメッセージは、番号だけでなく何をしたのかも記述しよう

### ISSUE THREAD

**Issue by norotime** [yagupi/k-board#20]
![2018-09-19 20 53 15](https://user-images.githubusercontent.com/7435505/45751694-145e5e80-bc4e-11e8-94c8-41690dc8256c.png)

@yagupi 増えました。w

**Comment by norotime** [comment]
@yagupi 番号だけでは、「一見何かがわかりません」

**Comment by yagupi** [comment]
なるほど、修正内容も文章で書くのですね！
次からそうします！
（増えて驚きました。笑）
