### ISSUE TITLE
likeはresourcesでまとめるかcomment内に完全に入れ子にするか再考する

### ISSUE THREAD

**Issue by norotime** [yagupi/k-board#5]
https://github.com/yagupi/k-board/blob/2b68b07bd1971a43e57d470884124a73c503c690/config/routes.rb#L6

@yagupi commentに完全にひもづくものであれば、入れ子にするのはありと思います。独立させておいても良いと思います。

**Comment by yagupi** [comment]
紛らわしいかもしれませんが、この「blogs/likes」はイイネ集ページへのルーティングです。
お気に入り登録用ルーティングは以下のように別に記載しています。
resources :likes, only: [:create, :destroy]
ご指摘のpointが違っていたらご教示ください。
