### ISSUE TITLE
createはnewとsaveを兼ねていることを理解して使おう

### ISSUE THREAD

**Issue by norotime** [yagupi/k-board#8]
https://github.com/yagupi/k-board/blob/2b68b07bd1971a43e57d470884124a73c503c690/app/controllers/blogs_controller.rb#L21

https://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-create

**Comment by yagupi** [comment]
まだインスタンス作成の段階で、後にsave処理があるため修正。
create　→　save
