### ISSUE TITLE
アソシエーションメソッドを使い一行で書こう

### ISSUE THREAD

**Issue by norotime** [yagupi/k-board#9]
https://github.com/yagupi/k-board/blob/2b68b07bd1971a43e57d470884124a73c503c690/app/controllers/blogs_controller.rb#L23

https://railsguides.jp/association_basics.html#has-many%E3%81%A7%E8%BF%BD%E5%8A%A0%E3%81%95%E3%82%8C%E3%82%8B%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89-collection-build-attributes

**Comment by yagupi** [comment]
この2行を、
  @blog = Blog.create(blog_params)
  @blog.user_id = current_user.id
アソシエーションメソッドで1行にまとめました。
  @blog = current_user.blogs.build(blog_params)

**Comment by norotime** [comment]
@yagupi 素晴らしい！

**Comment by norotime** [comment]
@yagupi イシューは対応完了したら、クローズしてくださいね。

**Comment by yagupi** [comment]
早速ありがとうございます。
正しい書き方で git push したら勝手にCloseされるのかテストを兼ねてみました。
Closeは自分でやるのですね＾＾；

**Comment by norotime** [comment]
@yagupi クローズされますよ。コミットメッセージの書き方が間違っているのだと思います。

**Comment by yagupi** [comment]
そうなのですね・・・書き方を変えてやってみます！

**Comment by yagupi** [comment]
multiple issuesのCloseの書き方ミスに気づきました。
単体は成功したので、後で複数で試してみます。
